spring:
  thymeleaf:
    cache: false
    content-type: text/html
    enabled: true
    encoding: UTF-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html

  application:
      name: micro-weather-report-eureka-feign-gateway-hystrix


server:
  tomcat:
    uri-encoding: utf-8
  port: 8094




eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

 # 必须添加这个配置开启
feign:
  hystrix:
    enabled: true










