spring:
  thymeleaf:
    cache: false
    content-type: text/html
    enabled: true
    encoding: UTF-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html

  application:
      name: micro-weather-report-eureka-feign-gateway


server:
  tomcat:
    uri-encoding: utf-8
  port: 8090




eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    eureka-server-read-timeout-seconds: 5000
    eureka-server-connect-timeout-seconds: 5000



