server:
  tomcat:
    uri-encoding: utf-8
  port: 8081



spring:
  application:
    name: micro-weather-city-eureka-client

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/