spring:
  application:
    name: micro-weather-eureka-client-feign-hystrix

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    eureka-server-connect-timeout-seconds: 5000
    eureka-server-read-timeout-seconds: 5000
server:
  port: 8093

