spring:
  application:
    name: micro-weather-config-server
    # 设置配置中心地址
  cloud:
    config:
      server:
        git:
          uri: https://github.com/EarthChen/weather-forecast.git
          # 设置仓库下的路径
          search-paths: config-repo

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    eureka-server-connect-timeout-seconds: 5000
    eureka-server-read-timeout-seconds: 5000

server:
  port: 8091



